-- PostgreSQL: schema da tabela fato
DROP TABLE IF EXISTS funcionarios_mensal CASCADE;

CREATE TABLE funcionarios_mensal (
    id_local                  INTEGER,
    contratado                INTEGER NOT NULL,
    id_centro_custo           INTEGER,
    id_cargo                  INTEGER,
    cargo                     TEXT,
    id_situacao               INTEGER,
    data_admissao             DATE,
    data_rescisao             DATE,
    id_sindicato              INTEGER,
    id_vinculo                INTEGER,
    motivo_desligamento       TEXT,
    id_horario                INTEGER,
    id_centro_custo_relativo  INTEGER,
    id_folha                  INTEGER,
    tipo_contrato             TEXT,
    cod_sap                   TEXT,
    matr_gestor               INTEGER,
    periodo_txt               INTEGER NOT NULL,
    bool_hc_colab_rd_clt      BOOLEAN,
    bool_desligado            BOOLEAN,
    bool_admitidos            BOOLEAN,
    bool_reg_valido           BOOLEAN,
    bool_atividade            BOOLEAN,
    bool_hc_colab_rd          BOOLEAN,
    bool_rotatividade         BOOLEAN,
    bool_transferencia        BOOLEAN,
    numero_vaga               INTEGER,
    periodo                   TEXT,
    periodo_data              DATE,
    tempo_casa_anos           DOUBLE PRECISION,
    tempo_desligamento_anos   DOUBLE PRECISION,
    faixa_tempo_casa          TEXT,
    flag_sem_gestor           BOOLEAN,
    PRIMARY KEY (contratado, periodo_txt)
);
